blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ PyDelhi WhatsApp
    url: https://chat.whatsapp.com/IUA2o1Xu8w8LmaZ8bw0nbb
    about: Please use the WhatsApp community to connect with fellow Pythonistas in and around Delhi/NCR.
  - name: ðŸ’¬ PyDelhi Telegram
    url: https://t.me/PyDelhi_official
    about: Please use the Telegram group to connect with fellow Pythonistas in and around Delhi/NCR.
  - name: Q/A Forum
    url: https://github.com/orgs/pydelhi/discussions
    about: Use the forum to ask questions about the meetup, help us with Sponsorship, or anything else.
